server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/user/**
        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/product/**
